language: java

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/8ff2fd7eb6a3e536bba3
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
